name: Print Environment
on:
  - workflow_call
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Context Data 🖨
        env:
          GITHUB_CONTEXT_JSON: ${{toJson(github)}}
        run: echo "$GITHUB_CONTEXT_JSON" | jq --color-output || true
      - name: Print GitHub Environment variables 🖨
        run: npx @bahmutov/print-env GITHUB
